# Generated by Django 6.0.3 on 2026-03-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='本金')),
                ('expected_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预期收益')),
                ('description', models.TextField(blank=True, verbose_name='策略描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '策略想法',
                'verbose_name_plural': '策略想法',
                'db_table': 'strategy_idea',
            },
        ),
    ]
